# Generated by Django 2.2.16 on 2021-09-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210916_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код доступа'),
        ),
    ]
