# Generated by Django 2.2.16 on 2021-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pk'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-pk'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-pk'], 'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
    ]
