# Generated by Django 2.2.16 on 2021-09-16 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210916_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Оценка не может быть больше 10 баллов'), django.core.validators.MinValueValidator(1, 'Оценка не может быть меньше 1 балла')]),
        ),
    ]
